### ISSUE TITLE
Spike:Add milestone info to ops-doc including how to add milestones

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-docs#7]
Goal is to use milestones for features/deliverables 

- [ ] Review options for milestone usage as provided by github
- [ ] propose in ops-doc the method to use
- [ ] iterate based on team feedback on PR

**Comment by msdisme** [comment]
Also concept of a label for items late added or late dropped. eg. osticket lable and

**Comment by larsks** [comment]
We talked on the call about using labels to mark tasks that are added to the sprint after the backlog planning meeting. If there's going to be more than one such label, I'd like to suggest using some sort of common prefix for those labels so that they are clearly identified as a set of related things. Something like:

- `added:osticket`
- `added:crisis`

Etc.

**Comment by msdisme** [comment]
- [ ] added_post_planning
- [ ] mention of the automation pieces
- [ ] how to use milestones
